lsaapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500, handler403, handler400
from django.contrib.sitemaps.views import sitemap

from core.auth.views import RegisterView, GuardianRegisterView, TeacherRegisterView
from core.auth.views import CustomLoginView, CustomLogoutView
from core.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from core.auth.views import teacher_dashboard, student_dashboard, guardian_dashboard
from core.views import custom_404, custom_500, custom_403, custom_400
from core.views import home, send_test_email
from core.views import AdminDashboardView, PromoteStudentView, programs, about, contact
from core.views import CreateNotificationView, NotificationListView
from core.views import SessionListView, SessionDetailView, SessionCreateView, SessionUpdateView, SessionDeleteView
from core.views import TermListView, TermDetailView, TermCreateView, TermUpdateView, TermDeleteView, activate_term_view
from core.views import promote_student, repeat_student, demote_student, mark_dormant_student, mark_left_student, mark_active, unenroll_student
from core.views import create_assessment, admin_assessment_list, approve_assessment, pending_assessments, view_assessment, admin_delete_assessment, assessment_submissions_list, class_subjects
from core.views import create_exam, admin_exam_list, approve_exam, pending_exams, view_exam, admin_delete_exam, exam_submissions_list
from core.views import broadsheets, termly_broadsheet, approve_termly_broadsheet, archive_termly_broadsheet, admin_leaderboard_view
from core.views import sessional_broadsheets, admin_sessional_broadsheet, approve_sessional_broadsheet, archive_sessional_broadsheet
from core.views import FeeAssignmentCreateView, FeeAssignmentListView, FeeAssignmentUpdateView, FeeAssignmentDetailView, FeeAssignmentDeleteView, StudentFeeRecordListView
from core.views import PaymentCreateView, PaymentListView, PaymentUpdateView, PaymentDetailView, PaymentDeleteView, FinancialRecordListView
from core.views import StudentClassEnrollmentView, StudentEnrollmentsView, message_inbox, grant_retake, message_thread, compose_message
from core.views import AssignSubjectView, AssignTeacherView, AssignClassSubjectView, ClassSubjectRolloverView, DeleteClassSubjectAssigmentView
from core.views import TeacherAssignmentListView, TeacherAssignmentRolloverView, TeacherAssignmentUpdateView, TeacherAssignmentDetailView, TeacherAssignmentDeleteView
from core.views import SubjectCreateView, SubjectListView, SubjectUpdateView, SubjectDetailView, SubjectDeleteView
from core.views import PostCreateView, PostUpdateView, PostDeleteView, ManagePostListView
from core.views import CategoryCreateView, CategoryUpdateView, ManageCategoryListView, TagCreateView, TagUpdateView, ManageTagListView
from core.student.views import StudentListView, StudentCreateView, StudentUpdateView, StudentDetailView, StudentDeleteView, BulkUpdateStudentsView, export_students, student_reports
from core.student.views import submit_assignment, start_assignment, take_assignment, autosubmit_beacon_assignment
from core.student.views import submit_assessment, start_assessment, take_assessment, autosubmit_beacon_assessment
from core.student.views import submit_exam, start_exam, take_exam, autosubmit_beacon_exam
from core.teacher.views import TeacherListView, TeacherCreateView, TeacherUpdateView, TeacherDetailView, TeacherDeleteView, TeacherBulkActionView, export_teachers, teacher_reports
from core.teacher.views import input_scores, broadsheet, sessional_broadsheet, mark_attendance, attendance_log, update_result, view_na_result, grade_essay_questions
from core.teacher.views import create_assignment, add_question, grade_assignment, assignment_submissions_list, update_assignment, delete_assignment, assignment_detail, assignment_list
from core.teacher.views import create_assessment, teacher_assessment_list, view_assessment, update_assessment, delete_assessment, grade_essay_assessment
from core.teacher.views import create_exam, teacher_exam_list, view_exam, update_exam, delete_exam, grade_essay_exam
from core.guardian.views import GuardianListView, GuardianCreateView, GuardianUpdateView, GuardianDetailView, GuardianDeleteView, GuardianBulkActionView
from core.guardian.views import financial_record_detail, view_termly_result, view_sessional_result, export_guardians, guardian_reports
from core.guardian.views import submit_assignment, submit_assessment, submit_exam
from core.guardian.views import view_assignment_result, view_assessment_result, view_exam_result
from core.classes.views import ClassListView, ClassCreateView, ClassUpdateView, ClassDetailView, ClassDeleteView, EnrollStudentView
from core.results.views import ResultCreateView, ResultListView, ResultUpdateView, ResultDetailView, ResultDeleteView
from core.subject_assignment.views import SubjectAssignmentListView, SubjectAssignmentCreateView, SubjectAssignmentUpdateView, SubjectAssignmentDetailView, SubjectAssignmentDeleteView
from core.blog.views import PostDetailView, PostListView, BlogSearchView
from core.blog.sitemaps import PostSitemap, CategorySitemap


sitemaps = {
    'posts': PostSitemap,
    'categories': CategorySitemap,
}

urlpatterns = [

    # Admin URL 
    path('admin/', admin.site.urls),

    # Home and Auth URLs
    path('', home, name='home'),
    path('programs/', programs, name='programs'),
    path('about-us/', about, name='about_us'),
    path('contact-us/', contact, name='contact_us'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/guardian/', GuardianRegisterView.as_view(), name='guardian_register'),
    path('register/teacher/', TeacherRegisterView.as_view(), name='teacher_register'),
    path('login/', CustomLoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', CustomLogoutView.as_view(template_name='auth/logout.html', next_page='home'), name='logout'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('send_test_email/', send_test_email, name='send_test_email'),
    
    # Blog URLS
    path('blog', PostListView.as_view(), name='post_list'),
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post_detail'), 
    path('category/<slug:category_slug>/', PostListView.as_view(), name='category_post_list'), 
    path('tag/<slug:tag_slug>/', PostListView.as_view(), name='tag_post_list'),          
    path('author/<str:username>/', PostListView.as_view(), name='author_post_list'),    
    path('search/', BlogSearchView.as_view(), name='blog_search'), 
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
    path('category/<slug:category_slug>/', PostListView.as_view(), name='category_post_list'),
    path('tag/<slug:tag_slug>/', PostListView.as_view(), name='tag_post_list'),
    path('author/<str:username>/', PostListView.as_view(), name='author_post_list'),
    path('posts/', ManagePostListView.as_view(), name='post_manage_list'),
    path('posts/create/', PostCreateView.as_view(), name='manage_post_create'),
    path('posts/<int:pk>/update/', PostUpdateView.as_view(), name='manage_post_update'),
    path('posts/<int:pk>/delete/', PostDeleteView.as_view(), name='manage_post_delete'),
    path('categories/', ManageCategoryListView.as_view(), name='manage_category_list'),
    path('categories/create/', CategoryCreateView.as_view(), name='manage_category_create'),
    path('categories/<int:pk>/update/', CategoryUpdateView.as_view(), name='manage_category_update'),
    path('tags/', ManageTagListView.as_view(), name='manage_tag_list'),
    path('tags/create/', TagCreateView.as_view(), name='manage_tag_create'),
    path('tags/<int:pk>/update/', TagUpdateView.as_view(), name='manage_tag_update'),

    # School Setup URLs
    path('setup/', AdminDashboardView.as_view(), name='school-setup'),

    path('create/', CreateNotificationView.as_view(), name='create_notification'),
    path('list/', NotificationListView.as_view(), name='notification_list'),

    path('sessions/', SessionListView.as_view(), name='session_list'),
    path('sessions/create/', SessionCreateView.as_view(), name='session_create'),
    path('sessions/update/<int:pk>/', SessionUpdateView.as_view(), name='session_update'),
    path('sessions/<int:pk>/', SessionDetailView.as_view(), name='session_detail'),
    path('sessions/<int:pk>/delete/', SessionDeleteView.as_view(), name='session_delete'),

    path('terms/', TermListView.as_view(), name='term_list'),
    path('terms/create/', TermCreateView.as_view(), name='term_create'),
    path('terms/update/<int:pk>/', TermUpdateView.as_view(), name='term_update'),
    path('terms/<int:pk>', TermDetailView.as_view(), name='term_detail'),
    path('terms/<int:pk>/delete/', TermDeleteView.as_view(), name='term_delete'),
    path('terms/<int:pk>/activate/', activate_term_view, name='term_activate'), 

    # Internal Messaging URLs

    path('messages/', message_inbox, name='message_inbox'),
    path('messages/compose/', compose_message, name='compose_message'),
    path('messages/thread/<int:thread_id>/', message_thread, name='message_thread'),

    # Enrollment URLs
    path('setup/enrol_student/', StudentClassEnrollmentView, name='enrol_student'),
    path('student/<int:student_id>/unenroll/<int:class_id>/', unenroll_student, name='unenroll_student'),

lsalms/urls.py
# lsalms/urls.py

from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'lsalms'

urlpatterns = [
    # === Admin "Mission Control" URL ===
    path('admin-dashboard/', views.LMSAdminDashboardView.as_view(), name='admin_lms_dashboard'),

    # === Teacher "Creator Hub" URLs ===
    path('teacher/course/create/', views.CourseCreateView.as_view(), name='course_create'),
    path('teacher/course/<slug:slug>/edit/', views.CourseUpdateView.as_view(), name='course_edit'),
    path('teacher/course/<slug:slug>/manage/', views.CourseManageView.as_view(), name='course_manage'),
    path('teacher/course/<int:pk>/publish/', views.course_publish, name='course_publish'),
    path('teacher/course/<int:course_id>/update-weights/', views.update_weights_view, name='update_weights'),
    path('builder/<slug:course_slug>/', views.course_builder_view, name='course_builder'),

    
    # URLs for adding components to the course builder (perfect for modals/HTMX)
    path('teacher/course/<int:course_id>/add-module/', views.ModuleCreateView.as_view(), name='module_create'),
    path('teacher/module/<int:module_id>/add-lesson/', views.LessonCreateView.as_view(), name='lesson_create'),
    path('teacher/module/update-order/', views.update_module_order, name='update_module_order'),
    path('teacher/lesson/<int:lesson_id>/add-content/', views.ContentBlockCreateView.as_view(), name='content_block_create'),
    path('api/reorder/modules/<int:course_id>/', views.update_module_order, name='api_update_module_order'),
    path('api/reorder/lessons/<int:module_id>/', views.update_lesson_order, name='api_update_lesson_order'),
    path('api/reorder/content-blocks/<int:lesson_id>/', views.update_content_block_order, name='api_update_content_block_order'),


    # UPDATE (Edit)
    path('teacher/module/<int:pk>/edit/', views.ModuleUpdateView.as_view(), name='module_edit'),
    path('teacher/lesson/<int:pk>/edit/', views.LessonUpdateView.as_view(), name='lesson_edit'),
    path('teacher/content/<int:pk>/edit/', views.ContentBlockUpdateView.as_view(), name='content_block_edit'),

    # DELETE
    path('admin/course/<int:pk>/delete/', views.course_delete, name='course_delete'),
    path('teacher/module/<int:pk>/delete/', views.module_delete, name='module_delete'),
    path('teacher/lesson/<int:pk>/delete/', views.lesson_delete, name='lesson_delete'),
    path('teacher/content/<int:pk>/delete/', views.content_block_delete, name='content_block_delete'),

    # === Student & Guardian Facing URLs ===
    path('course/<slug:slug>/', views.CourseDetailView.as_view(), name='course_detail'),
    path('lesson/<int:pk>/', views.LessonDetailView.as_view(), name='lesson_detail'),
    path('lesson/<int:pk>/complete/', views.mark_lesson_complete, name='mark_lesson_complete'),

    # === API URL for AI Integration ===
    path('api/ai-assist/', views.ai_content_generator_view, name='api_ai_assist'),
    path('api/get-subjects-for-class/', views.get_subjects_for_class_api, name='api_get_subjects_for_class'),

    # == Academy Hub URLs===
    path('academy/', views.OnlineAcademyHubView.as_view(), name='academy_hub'),
    path('academy/course/<slug:slug>/', views.AcademyCourseDetailView.as_view(), name='academy_course_detail'),
    path('academy/course/<int:course_id>/subscribe/', views.subscribe_to_course_view, name='subscribe_to_course'),
    path('academy/course/<slug:slug>/confirm/', views.CourseSubscriptionConfirmView.as_view(), name='course_subscription_confirm'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/assignment/forms.py
from django import forms
from core.models import Assignment, Question, AssignmentSubmission
from core.fields import AwareDateTimeField

class AssignmentForm(forms.ModelForm):

    due_date = AwareDateTimeField(
        required=False, 
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control'})
    )
    class Meta:
        model = Assignment
        fields = [
            'term', 'teacher', 'title', 'description', 'subject', 
            'class_assigned', 'due_date', 'duration', 'active',
            'result_field_mapping', 'shuffle_questions'
        ]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 2}),
            'class_assigned': forms.Select(attrs={'class': 'form-control'}),
            'subject': forms.Select(attrs={'class': 'form-control'}),
            'due_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'shuffle_questions': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_type', 'question_text', 'options', 'correct_answer']

    def clean(self):
        cleaned_data = super().clean()
        question_type = cleaned_data.get("question_type")
        question_text = cleaned_data.get("question_text")

        if not question_text:
            raise forms.ValidationError("Question text is required.")

        if question_type in ['SCQ', 'MCQ']:
            options = cleaned_data.get("options")
            correct_answer = cleaned_data.get("correct_answer")
            if not options:
                raise forms.ValidationError("Options must be provided for SCQ/MCQ.")
            if not correct_answer:
                raise forms.ValidationError("Correct answer is required for SCQ/MCQ.")
        elif question_type == 'ES':
            # No additional validation for essay
            cleaned_data['options'] = None
            cleaned_data['correct_answer'] = None

        return cleaned_data



class AssignmentSubmissionForm(forms.ModelForm):
    class Meta:
        model = AssignmentSubmission
        fields = ['answers']

core/attendance/forms.py
# forms.py

from django import forms
from ..models import Attendance

class AttendanceForm(forms.ModelForm):
    class Meta:
        model = Attendance
        fields = '__all__'

core/classes/forms.py
# forms.py

from django import forms
from core.models import Class

class ClassForm(forms.ModelForm):
    class Meta:
        model = Class
        fields = ['name', 'school_level', 'description', 'order']

core/enrollment/forms.py
from django import forms
from core.models import Enrollment, Student

class EnrollmentForm(forms.ModelForm):
    class Meta:
        model = Enrollment
        fields = ['student', 'class_enrolled', 'session', 'term', 'is_active']

    def __init__(self, *args, **kwargs):
        class_instance = kwargs.pop('class_instance', None)
        super().__init__(*args, **kwargs)

        if class_instance:
            # Exclude students already enrolled in the class for this session and term
            enrolled_students = class_instance.enrollment_set.values_list('student__user_id', flat=True)
            self.fields['student'].queryset = Student.objects.exclude(user_id__in=enrolled_students)

core/expense/forms.py
from django import forms
from ..models import Expense

class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = '__all__'

core/financial_record/forms.py
from django import forms
from ..models import FinancialRecord

class FinancialRecordForm(forms.ModelForm):
    class Meta:
        model = FinancialRecord
        fields = '__all__'

core/results/forms.py
# forms.py

from django import forms
from ..models import Result

class ResultForm(forms.ModelForm):
    class Meta:
        model = Result
        fields = '__all__'

core/subject/forms.py
# forms.py

from django import forms
from ..models import Subject

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['name', 'description', 'subject_weight']

core/templates/guardian/partials/_academics_pane.html
<!-- DEFINITIVE FILE: guardian/partials/_academics_pane.html -->
{% load message_filters %}

{% with student_tasks=students_data|get_item:student.pk %}
    
    {# --- ACTIVE TASKS SECTION --- #}
    {% with combined_active_tasks=student_tasks.assignments.active|add:student_tasks.assessments.active|add:student_tasks.exams.active %}
    <h5 class="fw-bold mb-3">Active Tasks ({{ combined_active_tasks|length }})</h5>
    <div class="list-group list-group-flush">
        {% for task in combined_active_tasks %}
        <div class="list-group-item d-flex justify-content-between align-items-center px-0">
            <div class="d-flex align-items-center">
                {% if task.type == 'assignment' %}<div class="quest-icon-sm bg-info-subtle text-info me-3"><i class="bi bi-journal-check"></i></div>
                {% elif task.type == 'assessment' %}<div class="quest-icon-sm bg-warning-subtle text-warning me-3"><i class="bi bi-pencil-square"></i></div>
                {% elif task.type == 'exam' %}<div class="quest-icon-sm bg-danger-subtle text-danger me-3"><i class="bi bi-file-earmark-check-fill"></i></div>
                {% endif %}
                <div>
                    <strong>{{ task.obj.title }}</strong>
                    <div class="small text-muted">{{ task.obj.subject.name }} | Due: {{ task.obj.due_date|date:"D, d M Y" }}</div>
                </div>
            </div>
            <div>
                <a href="{{ task.start_url }}?student_id={{ student.pk }}" class="btn btn-sm btn-primary">
                    {% if task.status == 'IN_PROGRESS' %}Continue{% else %}Start{% endif %}
                </a>
            </div>
        </div>
        {% empty %}
        <div class="list-group-item text-muted text-center py-4"><p class="mb-0">No active tasks found.</p></div>
        {% endfor %}
    </div>
    {% endwith %}

    <hr class="my-4">

    {# --- TASK HISTORY SECTION --- #}
    {% with combined_past_tasks=student_tasks.assignments.past|add:student_tasks.assessments.past|add:student_tasks.exams.past %}
    {% if combined_past_tasks %}
    <div class="accordion" id="task-history-accordion-{{ student.pk }}">
        <div class="accordion-item">
            <h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-history-{{ student.pk }}">Task History</button></h2>
            <div id="collapse-history-{{ student.pk }}" class="accordion-collapse collapse" data-bs-parent="#task-history-accordion-{{ student.pk }}">
                <div class="accordion-body p-0">
                    <div class="list-group list-group-flush">
                        {% for task in combined_past_tasks %}
                        <div class="list-group-item d-flex justify-content-between align-items-center px-0">
                            <div>
                                <strong>{{ task.obj.title }}</strong>
                                <div class="small text-muted">{{ task.obj.subject.name }} | {{ task.type|title }}</div>
                            </div>
                            <div class="text-end">
                                {% if task.status == "COMPLETED" %}
                                    
                                    {# Check for Assignments: They are graded if they have a 'grade' #}
                                    {% if task.type == 'assignment' %}
                                        {% if task.submission.grade is not None %}
                                            <div class="d-flex align-items-center">
                                                <div class="me-3 text-end"><div class="fw-bold text-success">{{ task.submission.grade|floatformat:1 }} / {{ task.obj.get_total_marks }}</div></div>
                                                <a href="{% url 'view_assignment_result' task.submission.id %}" class="btn btn-sm btn-outline-primary"><i class="fas fa-eye"></i></a>
                                            </div>
                                        {% else %}
                                            <span class="badge bg-warning text-dark">Pending Grade</span>
                                        {% endif %}
                                    
                                    {# Check for Assessments/Exams: They are graded if 'is_graded' is True #}
                                    {% else %}
                                        {% if task.submission.is_graded %}
                                            <div class="d-flex align-items-center">
                                                <div class="me-3 text-end"><div class="fw-bold text-success">{{ task.submission.score|floatformat:1 }} / {{ task.obj.get_total_marks }}</div></div>
                                                {% if task.type == 'assessment' %}<a href="{% url 'view_assessment_result' task.submission.id %}" class="btn btn-sm btn-outline-primary"><i class="fas fa-eye"></i></a>
                                                {% elif task.type == 'exam' %}<a href="{% url 'view_exam_result' task.submission.id %}" class="btn btn-sm btn-outline-primary"><i class="fas fa-eye"></i></a>
                                                {% endif %}
                                            </div>
                                        {% else %}
                                            <span class="badge bg-warning text-dark">Pending Grade</span>
                                        {% endif %}
                                    {% endif %}

                                {% elif task.status == "OVERDUE" %}
                                    <span class="badge bg-danger">Overdue</span>
                                {% else %}
                                    <span class="badge bg-secondary">Archived</span>
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% endwith %}
{% endwith %}

core/templates/guardian/partials/_lms_progress_pane.html
{% load lsalms_extras humanize %}

{% with lms_data=lms_student_data %}
    {% if lms_data %}
        
        <!-- School Class Learning Section -->
        {% if lms_data.internal %}
        <h5 class="mt-3 fw-bold">School Class Learning</h5>
        <p class="text-muted small">Progress in courses linked to {{ student.user.first_name }}'s regular class subjects.</p>
        <div class="row g-3">
            {% for enrollment in lms_data.internal %}
                <div class="col-md-6">
                    <div class="card h-100 lms-card shadow-sm">
                        <div class="card-body">
                            <h6 class="card-title fw-bold">{{ enrollment.course.get_course_title }}</h6>
                            <small class="text-muted d-block mb-3">Taught by: {{ enrollment.course.teacher.get_full_name }}</small>

                            <!-- Course Engagement Section -->
                            <div class="mb-3">
                                <label class="form-label small text-uppercase fw-bold text-muted">Course Engagement</label>
                                <div class="progress" style="height: 10px;" title="{{ enrollment.progress_percentage }}% Complete">
                                    <div class="progress-bar" role="progressbar" style="width: {{ enrollment.progress_percentage }}%;" aria-valuenow="{{ enrollment.progress_percentage }}"></div>
                                </div>
                                <div class="d-flex justify-content-between small mt-1">
                                    <span class="text-muted">{{ enrollment.progress_percentage }}% Complete</span>
                                    <span class="fw-bold">{{ enrollment.completed_lessons }} / {{ enrollment.total_lessons }} Lessons</span>
                                </div>
                            </div>
                            
                            <!-- Final Grade Section -->
                            <div class="mb-3">
                                <label class="form-label small text-uppercase fw-bold text-muted">Final Grade</label>
                                <div class="p-2 bg-light rounded text-center">
                                    {% if enrollment.grade_report and enrollment.grade_report.final_score is not None %}
                                        <h4 class="fw-bold mb-0 text-primary">{{ enrollment.grade_report.final_score|floatformat:0 }}<small>%</small></h4>
                                    {% else %}
                                        <h4 class="fw-bold mb-0 text-muted">N/A</h4>
                                        <small class="text-muted">Not yet graded</small>
                                    {% endif %}
                                </div>
                            </div>

                            <ul class="list-unstyled text-muted small mt-3 mb-0">
                                {% if enrollment.last_activity_date %}
                                    <li><i class="fas fa-history fa-fw me-1"></i> Last activity: {{ enrollment.last_activity_date|naturaltime }}</li>
                                {% else %}
                                    <li><i class="fas fa-hourglass-start fa-fw me-1"></i> Course not started yet</li>
                                {% endif %}
                            </ul>
                        </div>
                        <a href="{% url 'lsalms:course_detail' slug=enrollment.course.slug %}" class="stretched-link"></a>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% endif %}

        <!-- Online Academy Section (with the same new design) -->
        {% if lms_data.external %}
        <hr class="my-4">
        <h5 class="mt-3 fw-bold">Online Academy Subscriptions</h5>
        <div class="row g-3">
             {% for enrollment in lms_data.external %}
                <div class="col-md-6">
                    <div class="card h-100 lms-card shadow-sm border-success">
                        <div class="card-body">
                            <h6 class="card-title fw-bold">{{ enrollment.course.title }}</h6>
                            <small class="text-muted d-block mb-3">Subscription ends: {{ enrollment.subscription_end_date|date:"d M Y" }}</small>

                            <!-- Course Engagement Section -->
                            <div class="mb-3">
                                <label class="form-label small text-uppercase fw-bold text-muted">Course Engagement</label>
                                <div class="progress" style="height: 10px;" title="{{ enrollment.progress_percentage }}% Complete">
                                    <div class="progress-bar bg-success" role="progressbar" style="width: {{ enrollment.progress_percentage }}%;"></div>
                                </div>
                                <div class="d-flex justify-content-between small mt-1">
                                    <span class="text-muted">{{ enrollment.progress_percentage }}% Complete</span>
                                    <span class="fw-bold">{{ enrollment.completed_lessons }} / {{ enrollment.total_lessons }} Lessons</span>
                                </div>
                            </div>
                            
                            <!-- Final Grade Section -->
                            <div class="mb-3">
                                <label class="form-label small text-uppercase fw-bold text-muted">Final Grade</label>
                                <div class="p-2 bg-light rounded text-center">
                                    {% if enrollment.grade_report and enrollment.grade_report.final_score is not None %}
                                        <h4 class="fw-bold mb-0 text-success">{{ enrollment.grade_report.final_score|floatformat:0 }}<small>%</small></h4>
                                    {% else %}
                                        <h4 class="fw-bold mb-0 text-muted">N/A</h4>
                                        <small class="text-muted">Not yet graded</small>
                                    {% endif %}
                                </div>
                            </div>
                            <ul class="list-unstyled text-muted small mt-3 mb-0">
                                {% if enrollment.last_activity_date %}
                                    <li><i class="fas fa-history fa-fw me-1"></i> Last activity: {{ enrollment.last_activity_date|naturaltime }}</li>
                                {% else %}
                                    <li><i class="fas fa-hourglass-start fa-fw me-1"></i> Course not started yet</li>
                                {% endif %}
                            </ul>
                        </div>
                        <a href="{% url 'lsalms:course_detail' slug=enrollment.course.slug %}" class="stretched-link"></a>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% endif %}

    {% else %}
    <div class="text-center p-4 bg-light rounded">
        <i class="bi bi-bookshelf fs-1 text-muted"></i>
        <p class="mt-2 mb-0 fw-bold">{{ student.user.first_name }} is not yet enrolled in any active LMS courses.</p>
        <p class="text-muted small">Enrollment in school subject courses is automatic once a teacher publishes the course.</p>
    </div>
    {% endif %}
{% endwith %}

<style>
    /* Add this to a central CSS file or a <style> block in your base.html for best practice */
    .lms-card {
        transition: transform 0.2s ease-in-out, box-shadow 0.2s ease-in-out;
    }
    .lms-card:hover {
        transform: translateY(-5px);
        box-shadow: 0 8px 30px rgba(0,0,0,0.1) !important;
    }
</style>