lsaapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500, handler403, handler400
from django.contrib.sitemaps.views import sitemap

from core.auth.views import RegisterView, GuardianRegisterView, TeacherRegisterView
from core.auth.views import CustomLoginView, CustomLogoutView
from core.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from core.auth.views import teacher_dashboard, student_dashboard, guardian_dashboard
from core.views import custom_404, custom_500, custom_403, custom_400
from core.views import home, send_test_email
from core.views import AdminDashboardView, PromoteStudentView, programs, about, contact
from core.views import CreateNotificationView, NotificationListView
from core.views import SessionListView, SessionDetailView, SessionCreateView, SessionUpdateView, SessionDeleteView
from core.views import TermListView, TermDetailView, TermCreateView, TermUpdateView, TermDeleteView, activate_term_view
from core.views import promote_student, repeat_student, demote_student, mark_dormant_student, mark_left_student, mark_active, unenroll_student
from core.views import create_assessment, admin_assessment_list, approve_assessment, pending_assessments, view_assessment, admin_delete_assessment, assessment_submissions_list, class_subjects
from core.views import create_exam, admin_exam_list, approve_exam, pending_exams, view_exam, admin_delete_exam, exam_submissions_list
from core.views import broadsheets, termly_broadsheet, approve_termly_broadsheet, archive_termly_broadsheet, admin_leaderboard_view
from core.views import sessional_broadsheets, admin_sessional_broadsheet, approve_sessional_broadsheet, archive_sessional_broadsheet
from core.views import FeeAssignmentCreateView, FeeAssignmentListView, FeeAssignmentUpdateView, FeeAssignmentDetailView, FeeAssignmentDeleteView, StudentFeeRecordListView
from core.views import PaymentCreateView, PaymentListView, PaymentUpdateView, PaymentDetailView, PaymentDeleteView, FinancialRecordListView
from core.views import StudentClassEnrollmentView, StudentEnrollmentsView, message_inbox, grant_retake, message_thread, compose_message
from core.views import AssignSubjectView, AssignTeacherView, AssignClassSubjectView, ClassSubjectRolloverView, DeleteClassSubjectAssigmentView
from core.views import TeacherAssignmentListView, TeacherAssignmentRolloverView, TeacherAssignmentUpdateView, TeacherAssignmentDetailView, TeacherAssignmentDeleteView
from core.views import SubjectCreateView, SubjectListView, SubjectUpdateView, SubjectDetailView, SubjectDeleteView
from core.views import PostCreateView, PostUpdateView, PostDeleteView, ManagePostListView
from core.views import CategoryCreateView, CategoryUpdateView, ManageCategoryListView, TagCreateView, TagUpdateView, ManageTagListView
from core.student.views import StudentListView, StudentCreateView, StudentUpdateView, StudentDetailView, StudentDeleteView, BulkUpdateStudentsView, export_students, student_reports
from core.student.views import submit_assignment, start_assignment, take_assignment, autosubmit_beacon_assignment
from core.student.views import submit_assessment, start_assessment, take_assessment, autosubmit_beacon_assessment
from core.student.views import submit_exam, start_exam, take_exam, autosubmit_beacon_exam
from core.teacher.views import TeacherListView, TeacherCreateView, TeacherUpdateView, TeacherDetailView, TeacherDeleteView, TeacherBulkActionView, export_teachers, teacher_reports
from core.teacher.views import input_scores, broadsheet, sessional_broadsheet, mark_attendance, attendance_log, update_result, view_na_result, grade_essay_questions
from core.teacher.views import create_assignment, add_question, grade_assignment, assignment_submissions_list, update_assignment, delete_assignment, assignment_detail, assignment_list
from core.teacher.views import create_assessment, teacher_assessment_list, view_assessment, update_assessment, delete_assessment, grade_essay_assessment
from core.teacher.views import create_exam, teacher_exam_list, view_exam, update_exam, delete_exam, grade_essay_exam
from core.guardian.views import GuardianListView, GuardianCreateView, GuardianUpdateView, GuardianDetailView, GuardianDeleteView, GuardianBulkActionView
from core.guardian.views import financial_record_detail, view_termly_result, view_sessional_result, export_guardians, guardian_reports
from core.guardian.views import submit_assignment, submit_assessment, submit_exam
from core.guardian.views import view_assignment_result, view_assessment_result, view_exam_result
from core.classes.views import ClassListView, ClassCreateView, ClassUpdateView, ClassDetailView, ClassDeleteView, EnrollStudentView
from core.results.views import ResultCreateView, ResultListView, ResultUpdateView, ResultDetailView, ResultDeleteView
from core.subject_assignment.views import SubjectAssignmentListView, SubjectAssignmentCreateView, SubjectAssignmentUpdateView, SubjectAssignmentDetailView, SubjectAssignmentDeleteView
from core.blog.views import PostDetailView, PostListView, BlogSearchView
from core.blog.sitemaps import PostSitemap, CategorySitemap


sitemaps = {
    'posts': PostSitemap,
    'categories': CategorySitemap,
}

urlpatterns = [

    # Admin URL 
    path('admin/', admin.site.urls),

    # Home and Auth URLs
    path('', home, name='home'),
    path('programs/', programs, name='programs'),
    path('about-us/', about, name='about_us'),
    path('contact-us/', contact, name='contact_us'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/guardian/', GuardianRegisterView.as_view(), name='guardian_register'),
    path('register/teacher/', TeacherRegisterView.as_view(), name='teacher_register'),
    path('login/', CustomLoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', CustomLogoutView.as_view(template_name='auth/logout.html', next_page='home'), name='logout'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('send_test_email/', send_test_email, name='send_test_email'),
    
    # Blog URLS
    path('blog', PostListView.as_view(), name='post_list'),
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post_detail'), 
    path('category/<slug:category_slug>/', PostListView.as_view(), name='category_post_list'), 
    path('tag/<slug:tag_slug>/', PostListView.as_view(), name='tag_post_list'),          
    path('author/<str:username>/', PostListView.as_view(), name='author_post_list'),    
    path('search/', BlogSearchView.as_view(), name='blog_search'), 
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
    path('category/<slug:category_slug>/', PostListView.as_view(), name='category_post_list'),
    path('tag/<slug:tag_slug>/', PostListView.as_view(), name='tag_post_list'),
    path('author/<str:username>/', PostListView.as_view(), name='author_post_list'),
    path('posts/', ManagePostListView.as_view(), name='post_manage_list'),
    path('posts/create/', PostCreateView.as_view(), name='manage_post_create'),
    path('posts/<int:pk>/update/', PostUpdateView.as_view(), name='manage_post_update'),
    path('posts/<int:pk>/delete/', PostDeleteView.as_view(), name='manage_post_delete'),
    path('categories/', ManageCategoryListView.as_view(), name='manage_category_list'),
    path('categories/create/', CategoryCreateView.as_view(), name='manage_category_create'),
    path('categories/<int:pk>/update/', CategoryUpdateView.as_view(), name='manage_category_update'),
    path('tags/', ManageTagListView.as_view(), name='manage_tag_list'),
    path('tags/create/', TagCreateView.as_view(), name='manage_tag_create'),
    path('tags/<int:pk>/update/', TagUpdateView.as_view(), name='manage_tag_update'),

    # School Setup URLs
    path('setup/', AdminDashboardView.as_view(), name='school-setup'),

    path('create/', CreateNotificationView.as_view(), name='create_notification'),
    path('list/', NotificationListView.as_view(), name='notification_list'),

    path('sessions/', SessionListView.as_view(), name='session_list'),
    path('sessions/create/', SessionCreateView.as_view(), name='session_create'),
    path('sessions/update/<int:pk>/', SessionUpdateView.as_view(), name='session_update'),
    path('sessions/<int:pk>/', SessionDetailView.as_view(), name='session_detail'),
    path('sessions/<int:pk>/delete/', SessionDeleteView.as_view(), name='session_delete'),

    path('terms/', TermListView.as_view(), name='term_list'),
    path('terms/create/', TermCreateView.as_view(), name='term_create'),
    path('terms/update/<int:pk>/', TermUpdateView.as_view(), name='term_update'),
    path('terms/<int:pk>', TermDetailView.as_view(), name='term_detail'),
    path('terms/<int:pk>/delete/', TermDeleteView.as_view(), name='term_delete'),
    path('terms/<int:pk>/activate/', activate_term_view, name='term_activate'), 

    # Internal Messaging URLs

    path('messages/', message_inbox, name='message_inbox'),
    path('messages/compose/', compose_message, name='compose_message'),
    path('messages/thread/<int:thread_id>/', message_thread, name='message_thread'),

    # Enrollment URLs
    path('setup/enrol_student/', StudentClassEnrollmentView, name='enrol_student'),
    path('student/<int:student_id>/unenroll/<int:class_id>/', unenroll_student, name='unenroll_student'),

core/assessment/forms.py
# forms.py

from django import forms
from core.models import Assessment, OnlineQuestion, Term
from django.utils.timezone import now
import json


class AssessmentForm(forms.ModelForm):

    questions = forms.ModelMultipleChoiceField(
        queryset=OnlineQuestion.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    due_date = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control'}, format='%Y-%m-%dT%H:%M'),
        input_formats=['%Y-%m-%dT%H:%M']
    )
    duration = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'e.g., 60'}),
        min_value=1
    )

    class Meta:
        model = Assessment
        fields = [
            'title', 'short_description', 'class_assigned',
            'subject', 'term', 'due_date', 'duration',
            'result_field_mapping', 'shuffle_questions'  
        ]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter the title of the assessment'}),
            'short_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': 'Provide a brief description'}),
            'class_assigned': forms.Select(attrs={'class': 'form-select'}),
            'subject': forms.Select(attrs={'class': 'form-select'}),
            'duration': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'e.g., 45 for 45 minutes'}),
            'term': forms.Select(attrs={'class': 'form-select'}),
            'due_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'result_field_mapping': forms.Select(attrs={'class': 'form-control'}),
            'shuffle_questions': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['term'].queryset = Term.objects.all() 
            self.fields['is_online'].initial = True

        def clean_due_date(self):
            due_date = self.cleaned_data['due_date']
            if due_date <= now():
                raise forms.ValidationError("Due date must be in the future.")
            return due_date
            

class OnlineQuestionForm(forms.ModelForm):
    class Meta:
        model = OnlineQuestion
        fields = ['question_type', 'question_text', 'options', 'correct_answer', 'points']

    def clean(self):
        cleaned_data = super().clean()
        question_type = cleaned_data.get('question_type')
        points = cleaned_data.get('points')

        if question_type in ['SCQ', 'MCQ']:
            if not points:  # Catches None, 0, or empty
                cleaned_data['points'] = 1

        elif question_type == 'ES':
            if not points or points <= 0:
                self.add_error('points', 'A point value greater than zero is required for Essay questions.')
        
        return cleaned_data

    def clean_options(self):
        options = self.cleaned_data.get('options') # This should be a list if coming from view/JSONField
        question_type = self.cleaned_data.get('question_type')

        if question_type in ['SCQ', 'MCQ']:
            if not options or not isinstance(options, list) or len(options) < 1: # Allow at least one option
                raise forms.ValidationError("At least one option is required for SCQ/MCQ questions.")
        return options

    def clean_correct_answer(self):
        correct_answer_input = self.cleaned_data.get('correct_answer') # This is the string from the input field
        question_type = self.cleaned_data.get('question_type')
        options = self.cleaned_data.get('options') # This should be the list of option strings

        if question_type == 'SCQ':
            if not correct_answer_input:
                raise forms.ValidationError("A correct answer is required for Single Choice Questions.")
            if options and correct_answer_input not in options:
                raise forms.ValidationError("For Single Choice, the correct answer must be one of the provided options.")
        
        elif question_type == 'MCQ':
            if not correct_answer_input:
                raise forms.ValidationError("At least one correct answer is required for Multiple Choice Questions.")

            if ',' in correct_answer_input:
                individual_correct_answers = [ans.strip() for ans in correct_answer_input.split(',') if ans.strip()]
            else:
                individual_correct_answers = [ans.strip() for ans in correct_answer_input.split(' ') if ans.strip()]

            if not individual_correct_answers: # e.g., if input was just "," or " "
                 raise forms.ValidationError("Please provide valid correct answer(s) for MCQ.")

            if options: # Ensure options list is available for checking
                for ans_part in individual_correct_answers:
                    if ans_part not in options:
                        raise forms.ValidationError(
                            f"For Multiple Choice, the answer '{ans_part}' is not among the provided options. "
                            f"All correct answers must be from the options list: {', '.join(options)}."
                        )
            else: # Should not happen if clean_options runs first and validates options presence
                raise forms.ValidationError("Options are missing for this MCQ, cannot validate correct answer.")
            
            return correct_answer_input # Return the validated (possibly multi-part) string

        elif question_type == 'ES':
            # For Essay, correct_answer is optional (can be a model answer or rubric)
            # No specific validation here other than what ModelCharField imposes (e.g. max_length)
            pass 
            
        return correct_answer_input # Return original input for ES or if no specific validation was triggered


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        initial_options = self.initial.get('options')
        # This logic is for when the form is initialized with existing instance data
        # for an edit form, ensuring stringified JSON for options is parsed to a list.
        if self.instance and self.instance.pk and isinstance(self.instance.options, str):
            try:
                parsed_options = json.loads(self.instance.options)
                if isinstance(parsed_options, list):
                     pass # Rely on JSONField's behavior
            except (json.JSONDecodeError, TypeError):
                # self.initial['options'] = [] # Default to empty list if parsing fails
                pass
        elif isinstance(initial_options, str): # If 'options' passed in initial dict is a string
             try:
                self.initial['options'] = json.loads(initial_options)
             except json.JSONDecodeError:
                self.initial['options'] = []
    
  

core/attendance/forms.py
# forms.py

from django import forms
from ..models import Attendance

class AttendanceForm(forms.ModelForm):
    class Meta:
        model = Attendance
        fields = '__all__'

core/classes/forms.py
# forms.py

from django import forms
from core.models import Class

class ClassForm(forms.ModelForm):
    class Meta:
        model = Class
        fields = ['name', 'school_level', 'description', 'order']

core/expense/forms.py
from django import forms
from ..models import Expense

class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = '__all__'

core/financial_record/forms.py
from django import forms
from ..models import FinancialRecord

class FinancialRecordForm(forms.ModelForm):
    class Meta:
        model = FinancialRecord
        fields = '__all__'

core/templates/assignment/assignment_detail.html
<!-- assignments/assignment_detail.html -->
{% extends 'base.html' %}

{% block content %}
<div class="card my-5">
    <div class="card-header">
        <h3>{{ assignment.title }}</h3>
    </div>
    <div class="card-body">
        <p><strong>Description:</strong> {{ assignment.description }}</p>
        <p><strong>Class:</strong> {{ assignment.class_assigned.name }}</p>
        <p><strong>Subject:</strong> {{ assignment.subject.name }}</p>
        <p><strong>Due Date:</strong> {{ assignment.due_date }}</p>
        
        <h4>Questions</h4>
        <ul class="list-group">
            {% for question in assignment.questions.all %}
                <li class="list-group-item">
                    <strong>{{ question.question_text }}</strong>
                    <br>
                    <em>Type: {{ question.get_question_type_display }}</em>
                    {% if question.options_list %}
                        <ul>
                            {% for option in question.options_list %}
                                <li>{{ option }}</li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p><em>No options provided for this question.</em></p>
                    {% endif %}
                </li>
            {% empty %}
                <li class="list-group-item">No questions added yet.</li>
            {% endfor %}
        </ul>
        
        <a href="{% url 'teacher_dashboard' %}" class="btn btn-secondary mt-3">Back to Dashboard</a>
    </div>
</div>
{% endblock %}

core/templates/assignment/assignment_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h2>Your Assignments</h2>
        <a href="{% url 'create_assignment' %}" class="btn btn-success mb-3">Create New Assignment</a>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Due Date</th>
                    <th>Class</th>
                    <th>Subject</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for assignment in assignments %}
                <tr>
                    <td>{{ assignment.title }}</td>
                    <td>{{ assignment.description }}</td>
                    <td>{{ assignment.due_date }}</td>
                    <td>{{ assignment.class_assigned.name }}</td>
                    <td>{{ assignment.subject.name }}</td>
                    <td>
                        <a href="{% url 'update_assignment' assignment.id %}" class="btn btn-info btn-sm">Edit</a>
                        <a href="{% url 'delete_assignment' assignment.id %}" class="btn btn-danger btn-sm">Delete</a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="6" class="text-center">No assignments found.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

core/templates/assignment/create_assignment.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5" style="max-width: 80%;">
    <div class="card shadow-sm border-0">
        <div class="card-header bg-secondary text-white text-center py-3">
            <h3 class="text-white">Create a New Assignment</h3>
        </div>
        <div class="card-body">
            <form method="POST" action="{% url 'create_assignment' %}">
                {% csrf_token %}
                <div class="mb-4">
                    <label for="id_title">Title</label>
                    {{ form.title }}
                    {% if form.title.errors %}
                        <ul class="text-danger">
                            {% for error in form.title.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div class="mb-4">
                    <label for="id_description">Description</label>
                    {{ form.description }}
                    {% if form.description.errors %}
                        <ul class="text-danger">
                            {% for error in form.description.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div class="mb-4">
                    <label for="id_class_assigned">Class Assigned</label>
                    {{ form.class_assigned }}
                    {% if form.class_assigned.errors %}
                        <ul class="text-danger">
                            {% for error in form.class_assigned.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div class="mb-4">
                    <label for="id_subject">Subject</label>
                    {{ form.subject }}
                    {% if form.subject.errors %}
                        <ul class="text-danger">
                            {% for error in form.subject.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div class="mb-4">
                    <label for="id_due_date">Due Date</label>
                    {{ form.due_date }}
                    {% if form.due_date.errors %}
                        <ul class="text-danger">
                            {% for error in form.due_date.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>

                <h5 class="mt-4">Add Questions</h5>
                <div id="questions-container"></div>

                <div class="text-center mt-4">
                    <button type="button" id="add-question" class="btn btn-secondary">
                        <i class="bi bi-plus-circle"></i> Add Question
                    </button>
                </div>

                <div class="text-center mt-4">
                    <button type="submit" class="btn btn-primary btn-lg">
                        <i class="bi bi-plus-circle"></i> Create Assignment
                    </button>
                </div>
            </form>
            {% if errors %}
                <div class="alert alert-danger mt-4">
                    <ul>
                        {% for error in errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>
        <div class="text-end mb-3">
            <a href="{% url 'teacher_dashboard' %}" class="btn btn-secondary">
                <i class="bi bi-arrow-left"></i> Back to Dashboard
            </a>
        </div>
    </div>
</div>

<!-- JavaScript to handle adding questions -->
<script>
    document.addEventListener('DOMContentLoaded', function () {
    let questionCount = 0;

    function createQuestionForm() {
        questionCount++;
        const questionHtml = `
            <div class="card mb-3 question-card">
                <div class="card-body">
                    <h6>Question ${questionCount}</h6>
                    <div class="form-group">
                        <label for="question_type_${questionCount}">Question Type:</label>
                        <select name="question_type_${questionCount}" id="question_type_${questionCount}" class="form-control">
                            <option value="SCQ">Single Choice Question</option>
                            <option value="MCQ">Multiple Choice Question</option>
                            <option value="ES">Essay Question</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="question_text_${questionCount}">Question Text:</label>
                        <textarea name="question_text_${questionCount}" id="question_text_${questionCount}" class="form-control" rows="2" required></textarea>
                    </div>
                    <div class="form-group question-options" id="options_div_${questionCount}">
                        <label for="options_${questionCount}">Options (comma separated):</label>
                        <input type="text" name="options_${questionCount}" id="options_${questionCount}" class="form-control" placeholder="e.g. Option1, Option2, Option3" />
                        <small class="form-text text-muted">Required for SCQ and MCQ. Separate options with commas.</small>
                    </div>
                    <div class="form-group question-answer" id="answer_div_${questionCount}">
                        <label for="correct_answer_${questionCount}">Correct Answer:</label>
                        <input type="text" name="correct_answer_${questionCount}" id="correct_answer_${questionCount}" class="form-control" required />
                    </div>
                    <div class="form-group essay-answer d-none" id="essay_answer_div_${questionCount}">
                        <label for="essay_answer_${questionCount}">Suggested Answer (Optional):</label>
                        <textarea name="essay_answer_${questionCount}" id="essay_answer_${questionCount}" class="form-control" rows="4"></textarea>
                        <small class="form-text text-muted">Optional suggested answer for essay question.</small>
                    </div>
                    <button type="button" class="btn btn-danger remove-question">Remove Question</button>
                </div>
            </div>
        `;
        document.getElementById('questions-container').insertAdjacentHTML('beforeend', questionHtml);

        document.getElementById(`question_type_${questionCount}`).addEventListener('change', function () {
            toggleQuestionFields(questionCount);
        });
    }

    function toggleQuestionFields(count) {
        const questionType = document.getElementById(`question_type_${count}`).value;
        const optionsField = document.getElementById(`options_div_${count}`);
        const answerField = document.getElementById(`answer_div_${count}`);
        const essayAnswerField = document.getElementById(`essay_answer_div_${count}`);

        if (questionType === 'ES') {
            optionsField.classList.add('d-none');
            optionsField.querySelector('input').removeAttribute('required');
            answerField.classList.add('d-none');
            answerField.querySelector('input').removeAttribute('required');
            essayAnswerField.classList.remove('d-none');
        } else {
            optionsField.classList.remove('d-none');
            optionsField.querySelector('input').setAttribute('required', 'true');
            answerField.classList.remove('d-none');
            answerField.querySelector('input').setAttribute('required', 'true');
            essayAnswerField.classList.add('d-none');
        }
    }

    document.querySelector('form').addEventListener('submit', function (e) {
        e.preventDefault();
        const formData = new FormData(this);
        for (const [key, value] of formData.entries()) {
            console.log(key, value);
        }
        this.submit();
    });
    
    document.getElementById('add-question').addEventListener('click', createQuestionForm);

    document.getElementById('questions-container').addEventListener('click', function (e) {
        if (e.target.classList.contains('remove-question')) {
            e.target.closest('.question-card').remove();
            questionCount--;
        }
    });
});

</script>
{% endblock %}

core/templates/assignment/delete_assignment.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5">
    <div class="card">
        <div class="card-header">
            <h3>Delete Assignment</h3>
        </div>
        <div class="card-body">
            <p>Are you sure you want to delete the assignment "{{ assignment.title }}"?</p>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Yes, Delete</button>
                <a href="{% url 'teacher_dashboard' %}" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

core/templates/assignment/update_assignment.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h2>Update Assignment</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Update Assignment</button>
        </form>
    </div>
{% endblock %}